### ISSUE TITLE
Week one task

### ISSUE THREAD

**Issue by at15** [at15/cs433#1]
course website http://cs.sjtu.edu.cn/~yaobin/teaching/2015distr/index.html
- [x] find a journal, more than 8 pages after 2013, send it to TA for pre title 
- [x] pre, paper summary 5 minutes, start from week 3
- [x] a one page summary, due on week7

**Comment by at15** [comment]
some journals that are recommended by ccf
- TPDS IEEE Transactions on Parallel and Distributed Systems
- JPDC Journal of Parallel and Distributed Computing
- PARCO Parallel Computing 
- DC Distributed Computing

**Comment by at15** [comment]
chose 
- Decentralized Access Control with Anonymous Authentication of Data Stored in Clouds  http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6463404
-  EgoLP: Fast and Distributed Community Detection in Billion-Node Social Networks
  http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7022642

**Comment by gaocegege** [comment]
0.0你是电院的？

**Comment by at15** [comment]
@gaocegege 我只是选了电院的课, 我是一只材料狗。(为什么想到了在朋友圈里看到的 

> 突然发现我就像一只快乐的小松鼠在森林里跳呀跳。嗯，还是只公的

and this part is finished after a one page summary.
